### ISSUE TITLE
net is not defined error when unzipping

### ISSUE THREAD

**Issue by leoncc** [triniwiz/nativescript-zip#15]
Hi,

Using nativescript-zip plugin V2.0.4 and I get the following error on a Android 7.1.1:  
ERROR Error: Uncaught (in promise): **ReferenceError: net is not defined**
JS: ReferenceError: net is not defined
JS:     at file:///data/data/org.nativescript.phoneapp/files/app/tns_modules/nativescript-zip/zip.js:82:35
JS:     at new ZoneAwarePromise (file:///data/data/org.nativescript.phoneapp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:777:29)
JS:     at Function.Zip.unzipWithProgress (file:///data/data/org.nativescript.phoneapp/files/app/tns_modules/nativescript-zip/zip.js:80:16)
JS:     at Function.Zip.unzip 

Code is quite simple:
    const zipFilePath = fs.path.join(folder.path, "data.zip");
    const zipFile = fs.File.fromPath(zipFilePath);
    // dataFile.zippedData is the zipped data in memory - BASE64 string
    // for instance: UEsDBAoAAAAIAGqzp0ydJNfAvgEAAK8EAAATAAAAY3VzdG9tZ.........
    zipFile.writeTextSync(dataFile.zippedData,
			err=>{ console.log(err);}, 
			TextModule.encoding.ISO_8859_1); // I know this gets written to the file
    **Zip.unzip(zipFilePath, folder.path);** // result in above exception

Any ideas?

Thanks
Leon

**Comment by leoncc** [comment]
Not to worry, follow advice on issue #10, fixed now.
